import {
 CSSIcon,
 ReactIcon,
 HTMLIcon,
 AngularIcon,
 BabelIcon,
 BootstrapIcon,
 ChartIcon,
 DockerIcon,
 EslintIcon,
 ExpressIcon,
 GraphqlIcon,
 JavascriptIcon,
 jQueryIcon,
 MeteorIcon,
 MongodbIcon,
 MuiIcon,
 MysqlIcon,
 NestIcon,
 NextIcon,
 NginxIcon,
 NodejsIcon,
 NpmIcon,
 PostgresIcon,
 postmanIcon,
 ReduxIcon,
 RouterIcon,
 SassIcon,
 SocketIcon,
 SwaggerIcon,
 TypescriptIcon,
 WebpackIcon,
 QSMashup,
 QSExtension,
 QSWebApp,
} from './icons'

const SkillsList = [
 {name: 'HTML', icon: HTMLIcon},
 {name: 'CSS', icon: CSSIcon},
 {name: 'JavaScript', icon: JavascriptIcon},
 {name: 'jQuery', icon: jQueryIcon},
 {name: 'TypeScript', icon: TypescriptIcon},
 {name: 'React', icon: ReactIcon},
 {name: 'Redux', icon: ReduxIcon},
 {name: 'React Router', icon: RouterIcon},
 {name: 'Angular.js', icon: AngularIcon},
 {name: 'NodeJS', icon: NodejsIcon},
 {name: 'Express.js', icon: ExpressIcon},
 {name: 'MUI', icon: MuiIcon},
 {name: 'Bootstrap', icon: BootstrapIcon},
 {name: 'NPM', icon: NpmIcon},
 {name: 'Next', icon: NextIcon},
 {name: 'NestJS', icon: NestIcon},
 {name: 'Meteor', icon: MeteorIcon},
 {name: 'Chart.js', icon: ChartIcon},
 {name: 'GraphQL', icon: GraphqlIcon},
 {name: 'Socket.io', icon: SocketIcon},
 {name: 'Webpack', icon: WebpackIcon},
 {name: 'Nginx', icon: NginxIcon},
 {name: 'Babel', icon: BabelIcon},
 {name: 'ESLint', icon: EslintIcon},
 {name: 'SASS', icon: SassIcon},
 {name: 'Postgres', icon: PostgresIcon},
 {name: 'MySQL', icon: MysqlIcon},
 {name: 'MongoDB', icon: MongodbIcon},
 {name: 'Docker', icon: DockerIcon},
 {name: 'Postman', icon: postmanIcon},
 {name: 'Swagger', icon: SwaggerIcon},
 {name: 'QlikSense Extension', icon: QSExtension},
 {name: 'QlikSense Mashup', icon: QSMashup},
 {name: 'QlikSense Webapp', icon: QSWebApp},
]

export default SkillsList
